### PR TITLE
Fixes to age structure (WHK, BLF, TAU, YTF) and reasonability (COD, SUF, LOB, HER)

### PR DESCRIPTION
**Pull request by RGamble1**
8 groups were tweaked.  The age structures of WHK, BLF, TAU and YTF over time were fixed to prevent the almost complete decimation of older age classes in a year or two when fishing was turned on.  HER's Initial Biomass was increased to be more in line with assessment estimates (higher biomass than we originally had them at).  This benefited a number of other species.  And then COD and SUF were tweaked to lower their curved near the end and this had a benefit on lobster. @jcaracappa1 @andybeet

### CODE REVIEW

**Comment by andybeet** [comment]
@RGamble1 i think we want to merge this into dev first

**Comment by jcaracappa1** [comment]
@RGamble1 It appears that COD had two Clearance Rate values dropped. (10 instead of 12) . I think we need to fix that and rerun the model before merging. 

I think the balance between HER and ZL is a little off after looking at changes since v2.2. It's probably a top down issue. Howe sensitive were HER to changes?

**Comment by RGamble1** [comment]
@jcaracappa1 Good catch on the Cod, no idea how that happened.  

Will check HER and ZL.  When you asked if HER was sensitive to changes, which changes did you mean?

**Comment by jcaracappa1** [comment]
This looks good @andybeet

**Review by andybeet — APPROVED** [review]

**Comment by andybeet** [comment]
@jcaracappa1 you need to approve this

**Pull request merged**
