### PR TITLE
Ne groundfish spatial

### PR DESCRIPTION
**Pull request by jcaracappa1**
## Summary
Utilities for manipulating spatial distribution parameters in the biology.prm and init.nc input files. Reference points for spatial biomass. Corrections to the seasonal movement parameters and initial abundance distributions.

## New R Scripts/Functions
- call_spatial_comaprisons.R : Script to create spatial comparisons for sets of runs using the atlantisprocessing package
- ddepend_batch_run.R : Script to generate a run set on a VM for testing distribution parameters
- edit_param_ddepend.R : Function to edit ddepend parameters
- edit_param_env_move.R : Function to edit min/max temperature and salinity bounds
- edit_param_init_dist.R : Function to edit initial conditions spatial distribution
- edit_param_seasonal_movement.R : Function to edit Fxxx_Sy parameters for prescribed movement
- get_init_spatial_dist.R :  Script to extract spatial distribution data from initial conditions
- get_param_seasonal_migration.R : Deleted and replaced by edit_param_seasonal_movement.R
- rescale_groundfish_scallop_spatial.R : Script to edit the seasonal movement and intitial distributions based on a survey reference dataset
- scale_forcing_ts.r : Andy's function to scale ts files

## R Script/Function changes
- call_neus_post_prcocess/call_run_comparison cleanup old arguments
- make_spatial_reference.R : Update input file for survey to add season

## Parameter Files
- at_biology.prm : Updated seasonal movement parameters
- neus_init.nc : Updated intial spatial distributions

## Other
- landings_by_box_species.rds : Reference file for spatial landings
- seasonal_movements.csv : Reference for seasonal movement parameters
- spatial_reference_initial_conditions.R : based on earliest survdat entries by species
- spatial_reference_survdat_2011_2021.rds : spatial biiomass for 2011 to 2021

### CODE REVIEW

**Comment by jcaracappa1** [comment]
@RGamble1 @andybeet part of the ongoing branch cleanup.

**Comment by jcaracappa1** [comment]
Joe_Proj/Atlantis_Runs/NE_groundfish_new_movement_2

**Comment by jcaracappa1** [comment]
[ NE_groundfish_new_movement_2Model_Comparison_Biomass.pdf](https://github.com/user-attachments/files/16715001/NE_groundfish_new_movement_2Model_Comparison_Biomass.pdf)

**Comment by jcaracappa1** [comment]
Updated WOL spatial distribution and calibrated affected species.

**Comment by andybeet** [comment]
new plots: [rescale_spatial_1bModel_Comparison_Biomass.pdf](https://github.com/user-attachments/files/16874766/rescale_spatial_1bModel_Comparison_Biomass.pdf)

**Comment by RGamble1** [comment]
Looks good to me @jcaracappa1 @andybeet.

Merging

**Pull request merged**
